development: &default
  adapter: postgresql
  encoding: unicode
  database: sprockets_test
  pool: 5
  username: postgres
  password: postgres
  min_messages: warning
  prepared_statements: false
  host: 127.0.0.1

test: &test
  <<: *default
  database: sprockets_test_test
